name: Supabase Keep Alive (Test)

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点执行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Run Keep Alive Test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
        run: |
          echo "Pinging Supabase..."
          curl -s -X GET "${SUPABASE_URL}/rest/v1/${SUPABASE_TABLE}?limit=5" \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY"